---------------------------
-- Test data population
---------------------------
-- insert users
INSERT INTO `playlisted_db`.`users` (`user_id`, `user_name`, `user_password`, `created_at`, `updated_at`) VALUES (default, 'Jenni', 'pwd', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
INSERT INTO `playlisted_db`.`users` (`user_id`, `user_name`, `user_password`, `created_at`, `updated_at`) VALUES (default, 'Becky', 'pwd', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
INSERT INTO `playlisted_db`.`users` (`user_id`, `user_name`, `user_password`, `created_at`, `updated_at`) VALUES (default, 'Morgan', 'pwd', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
INSERT INTO `playlisted_db`.`users` (`user_id`, `user_name`, `user_password`, `created_at`, `updated_at`) VALUES (default, 'James', 'pwd', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
INSERT INTO `playlisted_db`.`users` (`user_id`, `user_name`, `user_password`, `created_at`, `updated_at`) VALUES (default, 'SuperUser', 'pwd', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

select * from users;

-- insert songs
INSERT INTO `playlisted_db`.`songs` (`song_title`, `artist_name`, `date_released`,`mood`, `energy`, `genre`, `created_at`, `updated_at`) 
VALUES ("Come Sail Away", "Styx",  "2002/02/02", "Ecstatic", "0.9", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Waves of Galveston", "Iron and Wine", "2001-01-01", "Sad", "0.2", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("London Hymn", "Josh Groban", "2010-10-10", "Meh", "0.3", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Ave Maria", "Josh Groban", "2010-10-10", "Meh", "0.3", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Everybody's Changing", "Keane", "2011-11-11", "Angry", "0.7", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Yam Yam", "No Vacation", "2017-01-01", "Happy", "0.7", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Deep Sea Dive", "Snail Mail", "2018-06-08", "Sad", "0.4", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Space Song", "Beach House", "2015-01-01", "Meh", "0.5", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Flaming Hot Cheetos", "Clairo", "2018-01-01", "Happy", "0.6", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("When the Night is Over", "Lord Heron", "2018-04-01", "Meh", "0.5", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Marry Me, Archie", "Alvvays", "2014-01-01", "Happy", "0.7", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Mistake", "Middle Kids", "2018-01-01", "Angry", "0.8", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Edge of Town", "Middle Kids", "2018-01-01", "Meh", "0.6", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Smother", "Daughter", "2013-01-01", "Sad", "0.3", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Weak", "WET", "2016-01-01", "Sad", "0.3", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Don't Wanna be Your Girl", "WET", "2016-01-01", "Sad", "0.3", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("One of These Days", "Bedouine", "2018-01-01", "Happy", "0.2","Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Chinatown", "Girlpool", "2015-01-01", "Meh", "0.4", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Cut Your Bangs", "Girlpool", "2015-01-01", "Sad", "0.3", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Depreston", "Courtney Barnett", "201501-01", "Happy", "0.3", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Cool", "Soccer Mommy", "2018-03-01", "Happy", "0.5", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Shark Smile", "Big Thief", "2017-06-09", "Happy", "0.6", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Paul", "Big Thief", "2016-01-01", "Sad", "0.2", "Easy Listening", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Believer", "Imagine Dragons", "2017-01-01", "Happy", "0.5", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Celebrity Skin", "Hole", "2009-01-01", "Meh", "0.5", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("First to Love", "Blaqk Audio", "2016-07-08", "Happy", "0.5", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("The Gutter", "Coheed and Cambria", "2018-08-16", "Sad", "0.8", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Photograph", "Nickelback", "2005-01-01", "Sad", "0.6", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("How You Remind Me", "Nickleback", "2001-01-01", "Meh", "0.5", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Rockstar", "Nickleback", "2005-01-01", "Angry", "0.8", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Hurt Yourself", "Beyonce", "2016-01-01", "Angry", "1.0", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Aurelia", "AFI", "2017-01-01", "Angry", "0.7", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Livin' On A Prayer", "Bon Jovi", "1986-01-01", "Ecstatic", "0.7", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Smells Like Teen Spirit", "Nirvana", "1991-01-01", "Angry", "0.8", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Young Volcanoes", "Fall Out Boy", "2013-01-01", "Happy", "0.7", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Save Rock and Roll", "Fall Out Boy", "2013-01-01", "Meh", "0.6", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Just One Yesterday", "Fall Out Boy", "2013-01-01", "Happy", "0.6", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("My Songs Know What You Did In The Dark", "Fall Out Boy", "2013-01-01", "Angry", "0.9", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Sugar, We're Going Down", "Fall Out Boy", "2009-01-01", "Happy", "0.8", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Bohemian Rhapsody", "Queen", "1975-01-01", "Happy", "0.7", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("We Will Rock You", "Queen", "1977-01-01", "Ecstatic", "0.9", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Go Your Own Way", "Fleetwood Mac", "1977-01-01", "Happy", "0.6", "Rock", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Bad Romance", "Lady Gaga", "2009-01-01", "Meh", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Love Game", "Lady Gaga", "2008-01-01", "Happy", "0.8", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Poker Face", "Lady Gaga", "2008-01-01", "Happy", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("We Can't Stop", "Miley Cyrus", "2013-01-01", "Ecstatic", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Party In The USA", "Miley Cyrus", "2009-01-01", "Happy", "0.6", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("TGIF", "Katy Perry", "2010-01-01", "Ecstatic", "1.0", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Fireworks", "Katy Perry", "2010-01-01", "Ecstatic", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("One Last Time", "Ariana Grande", "2014-01-01", "Happy", "0.5", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Dangerous Woman", "Ariana Grande", "2016-05-20", "Meh", "0.4", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Look What You Made Me Do", "Taylor Swift", "2017-01-01", "Angry", "0.6", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Shake It Off", "Taylor Swift", "2014-01-01", "Ecstatic", "0.8", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Hit Me Baby, One More Time", "Britney Spears", "1998-01-01", "Sad", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Piece of Me", "Britney Spears", "2007-01-01", "Happy", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Toxic", "Britney Spears", "2003-01-01", "Happy", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Hands To Myself", "Selena Gomez", "2015-01-01", "Meh", "0.5", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Fetish", "Selena Gomez", "2017-01-01", "Meh", "0.4", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Breakaway", "Kelly Clarkson", "2004-11-30", "Sad", "0.2", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Girls Like You", "Maroon 5", "2017-01-01", "Ecstatic", "0.7", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Sugar", "Maroon 5", "2014-01-01", "Happy", "0.6", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("One Kiss", "Dua Lipa", "2018-01-01", "Ecstatic", "0.8", "Pop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("In My Feelings", "Drake", "2018-01-01", "Happy", "0.7", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Nice For What", "Drake", "2018-01-01", "Happy", "0.6", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Fade", "Kanye West", "2016-01-01", "Meh", "0.7", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Father Outstretch Your Hands Pt. 2", "Kanye West", "2016-06-07", "Ecstatic", "0.9", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Six Foot Seven Foot", "Lil Wayne", "2010-12-16", "Happy", "0.8", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("I Mean It", "G-Eazy", "2014-05-13", "Meh", "0.4", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Self-Care", "Mac Miller", "2018-07-12", "Meh", "0.3", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Bodak Yellow", "Cardi B", "2017-06-16", "Ecstatic", "1.0", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Be Careful", "Cardi B", "2018-03-29", "Sad", "0.5", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Bartier Cardi", "Cardi B", "2017-12-22", "Ecstatic", "0.9", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Chun-Li", "Nicki Minaj", "2018-04-12", "Happy", "0.8", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Moment For Life", "Nicki Minaj", "2010-12-07", "Happy", "0.5", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Anaconda", "Nicki Minaj", "2014-08-04", "Ecstatic", "1.0", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Love On Top", "Beyonce", "2011-10-16", "Happy", "0.6", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Crazy In Love", "Beyonce", "2003-05-18", "Ecstatic", "0.8", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("DNA", "Kendrick Lamar", "2017-04-14", "Angry", "0.9", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Humble", "Kendrick Lamar", "2017-03-30", "Angry", "0.8", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Rude Boy", "Rihanna", "2010-02-19", "Happy", "0.8", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Love On The Brain", "Rihanna", "2016-01-27", "Sad", "0.4", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Sisters", "Future", "2015-01-01", "Meh", "0.5", "rap-hip-hop", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Sleep", "Eric Whitacre", "2010-01-01", "Meh", "0.5", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Ave Maria", "Josh Groban", "2007-01-01", "Sad", "0.7", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Lux Aurumque", "Eric Whitacre", "2010-01-01", "Meh", "0.3", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("London Hymn", "Josh Groban", "2010-01-01", "Meh", "0.5", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("when david heard", "Eric Whitacre", "2012-01-01", "Sad", "0.2", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Come What May", "Nicole Kidman and Ewan McGregor", "2008-01-01", "Ecstatic", "0.9", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Beethoven's 5th Symphony", "Ludwig Van Beethoven", "1808-12-22", "Happy", "0.7", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Hallelujah", "Lindsey Stirling", "2015-12-07", "Meh", "0.2", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("The Show Must Go On", "Celine Dion, Lindsey Stirling ", "2016-05-20", "Sad", "0.8", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("A Thousand Years", "The Piano Guys", "2012-05-09", "Happy", "0.5", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("The Hobbit Cover", "The Piano Guys", "2012-11-20", "Sad", "0.2", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Fight Song", "The Piano Guys", "2015-10-29", "Happy", "0.9", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Bella's Lullaby", "Carter Burwell", "2008-01-01", "Sad", "0.1", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Pokemon Theme", "Kurt Hugo Schneider, Lindsey Stirling", "2001-01-01", "Ecstatic", "1.0", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Hallelujah", "Il Divo", "2008-11-10", "Sad", "0.6", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Mama", "Il Divo", "2004-01-01", "Sad", "0.3", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("Regresa a Mi", "Il Divo", "2004-01-01", "Sad", "0.7", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
       ("The Seal Lullaby ", "Eric Whitacre", "2010-01-01", "Happy", "0.1", "Classical", CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3))
;


select * from songs;